name: TubsStatusPlugin
version: '${project.version}'
main: de.tubyoub.statusplugin.StatusPlugin
api-version: 1.20
author: TubYoub
commands:
  status:
    description: Set a player's status, get info, get help, reload the plugin, set/reset max length
permissions:
  StatusPlugin.setStatus:
    description: Allows setting own status. (default player)
    default: true
  StatusPlugin.formatting:
    description: Allows using formatting codes such as &l,... (default op)
    default: op
  StatusPlugin.admin.setStatus:
    description: Allows setting other players' statuses. (default op)
    default: op
  StatusPlugin.admin.reload:
    description: Allows reloading statuses. (default op)
    default: op
  StatusPlugin.admin.setMaxlength:
    description: Allows setting the maximum length of statuses.
    default: op
  StatusPlugin.admin.resetMaxlength:
    description: Allows resetting the maximum length of statuses to default.
    default: op